### ISSUE TITLE
Issue about the last rule

### ISSUE THREAD

**Issue by ThatOneCalculator** [rose-pine/rose-pine-template#1]
Sometimes for progs like GTK3 and GRUB, there should be distinctions for versions because people use multiple versions of those programs and there can be confusion if, for example, someone is using GRUB1 and trying to apply a GRUB2 theme.

**Comment by mvllow** [comment]
having the version within the readme is perfectly fine. as far as the repo name - i believe following dracula's approach (https://github.com/dracula/gtk) by having folders with the corresponding version would be ideal. let me know if you think this is feasible
